import { connectDB, closeDB } from "../config/db";

const bangladeshShelters = [
  {
    name: "Patenga Coastal Cyclone Shelter",
    code: "CTG-SHELTER-001",
    location: { type: "Point", coordinates: [91.7832, 22.2384] },
    address: "Patenga Sea Beach Road",
    division: "Chattogram",
    district: "Chattogram",
    upazila: "Patenga",
    capacity: 1500,
    currentOccupancy: 1200,
    status: "OPEN",
    amenities: {
      hasCleanWater: true,
      hasElectricity: true,
      hasGenerator: true,
      hasMedicalFacility: true,
      separateWomenSpace: true,
    },
    contactPerson: { name: "Commander Ashraf Uddin", phone: "01819001122" },
  },
  {
    name: "Cox's Bazar Cyclone Refuge Center",
    code: "CXB-SHELTER-002",
    location: { type: "Point", coordinates: [91.9796, 21.4272] },
    address: "Marine Drive Road, Kalatali",
    division: "Chattogram",
    district: "Cox's Bazar",
    upazila: "Sadar",
    capacity: 1200,
    currentOccupancy: 450,
    status: "OPEN",
    amenities: {
      hasCleanWater: true,
      hasElectricity: true,
      hasGenerator: true,
      hasMedicalFacility: false,
      separateWomenSpace: true,
    },
    contactPerson: { name: "Saleh Ahmed", phone: "01711992233" },
  },
  {
    name: "Bhola Island Primary Relief Hub",
    code: "BHL-SHELTER-003",
    location: { type: "Point", coordinates: [90.6432, 22.6859] },
    address: "Char Fasson Road",
    division: "Barishal",
    district: "Bhola",
    upazila: "Bhola Sadar",
    capacity: 800,
    currentOccupancy: 800,
    status: "FULL",
    amenities: {
      hasCleanWater: true,
      hasElectricity: false,
      hasGenerator: true,
      hasMedicalFacility: false,
      separateWomenSpace: true,
    },
    contactPerson: { name: "Kibriya Hossain", phone: "01912334455" },
  },
  {
    name: "Sunamganj Flood Shelter (Chhatak)",
    code: "SNM-SHELTER-004",
    location: { type: "Point", coordinates: [91.6705, 25.0388] },
    address: "Surma River Bank Road",
    division: "Sylhet",
    district: "Sunamganj",
    upazila: "Chhatak",
    capacity: 600,
    currentOccupancy: 200,
    status: "OPEN",
    amenities: {
      hasCleanWater: true,
      hasElectricity: true,
      hasGenerator: false,
      hasMedicalFacility: true,
      separateWomenSpace: true,
    },
    contactPerson: { name: "Abdul Mannan", phone: "01715667788" },
  },
  {
    name: "Feni Girls High School Shelter",
    code: "FNI-SHELTER-005",
    location: { type: "Point", coordinates: [91.4027, 23.0159] },
    address: "SSK Road, Feni Sadar",
    division: "Chattogram",
    district: "Feni",
    upazila: "Feni Sadar",
    capacity: 1000,
    currentOccupancy: 350,
    status: "OPEN",
    amenities: {
      hasCleanWater: true,
      hasElectricity: true,
      hasGenerator: true,
      hasMedicalFacility: true,
      separateWomenSpace: true,
    },
    contactPerson: { name: "Nasima Begum", phone: "01812334455" },
  },
  {
    name: "Satkhira Coastal Refuge Compound",
    code: "STK-SHELTER-006",
    location: { type: "Point", coordinates: [89.0700, 22.3500] },
    address: "Shyamnagar Coastal Embankment",
    division: "Khulna",
    district: "Satkhira",
    upazila: "Shyamnagar",
    capacity: 900,
    currentOccupancy: 600,
    status: "OPEN",
    amenities: {
      hasCleanWater: true,
      hasElectricity: false,
      hasGenerator: true,
      hasMedicalFacility: false,
      separateWomenSpace: true,
    },
    contactPerson: { name: "Gazi Mijanur", phone: "01718990011" },
  },
  {
    name: "Khulna Disaster Prep Center",
    code: "KLN-SHELTER-007",
    location: { type: "Point", coordinates: [89.5400, 22.8200] },
    address: "Rupsha Bridge Bypass",
    division: "Khulna",
    district: "Khulna",
    upazila: "Rupsha",
    capacity: 1100,
    currentOccupancy: 400,
    status: "OPEN",
    amenities: {
      hasCleanWater: true,
      hasElectricity: true,
      hasGenerator: true,
      hasMedicalFacility: true,
      separateWomenSpace: true,
    },
    contactPerson: { name: "Rabeya Sultana", phone: "01911223344" },
  },
  {
    name: "Barishal Sadar Flood Center",
    code: "BSL-SHELTER-008",
    location: { type: "Point", coordinates: [90.3667, 22.7000] },
    address: "Band Road, Kirtankhola Bank",
    division: "Barishal",
    district: "Barishal",
    upazila: "Barishal Sadar",
    capacity: 950,
    currentOccupancy: 300,
    status: "OPEN",
    amenities: {
      hasCleanWater: true,
      hasElectricity: true,
      hasGenerator: false,
      hasMedicalFacility: true,
      separateWomenSpace: true,
    },
    contactPerson: { name: "Fazlur Rahman", phone: "01817665544" },
  },
  {
    name: "Dhaka High-School Emergency Shelter",
    code: "DHK-SHELTER-009",
    location: { type: "Point", coordinates: [90.4125, 23.8103] },
    address: "Uttara Sector 4, Dhaka",
    division: "Dhaka",
    district: "Dhaka",
    upazila: "Uttara",
    capacity: 2000,
    currentOccupancy: 500,
    status: "OPEN",
    amenities: {
      hasCleanWater: true,
      hasElectricity: true,
      hasGenerator: true,
      hasMedicalFacility: true,
      separateWomenSpace: true,
    },
    contactPerson: { name: "Syed Tanvir", phone: "01713334455" },
  },
  {
    name: "Sylhet Govt College Flood Refuge",
    code: "SYL-SHELTER-010",
    location: { type: "Point", coordinates: [91.8687, 24.8949] },
    address: "Tilagarh, Sylhet",
    division: "Sylhet",
    district: "Sylhet",
    upazila: "Sylhet Sadar",
    capacity: 1000,
    currentOccupancy: 850,
    status: "OPEN",
    amenities: {
      hasCleanWater: true,
      hasElectricity: true,
      hasGenerator: false,
      hasMedicalFacility: true,
      separateWomenSpace: true,
    },
    contactPerson: { name: "Mahbubur Rashid", phone: "01611223344" },
  },
  {
    name: "Teknaf Marine Drive Cyclone Center",
    code: "TKF-SHELTER-011",
    location: { type: "Point", coordinates: [92.2985, 20.8647] },
    address: "Shah Porir Dwip Road",
    division: "Chattogram",
    district: "Cox's Bazar",
    upazila: "Teknaf",
    capacity: 750,
    currentOccupancy: 700,
    status: "OPEN",
    amenities: {
      hasCleanWater: true,
      hasElectricity: false,
      hasGenerator: true,
      hasMedicalFacility: false,
      separateWomenSpace: true,
    },
    contactPerson: { name: "Nurul Islam", phone: "01815556677" },
  },
  {
    name: "Sandwip Island Haven Shelter",
    code: "SDP-SHELTER-012",
    location: { type: "Point", coordinates: [91.4321, 22.4912] },
    address: "Sandwip Jetty Road",
    division: "Chattogram",
    district: "Chattogram",
    upazila: "Sandwip",
    capacity: 1300,
    currentOccupancy: 1100,
    status: "OPEN",
    amenities: {
      hasCleanWater: true,
      hasElectricity: false,
      hasGenerator: true,
      hasMedicalFacility: true,
      separateWomenSpace: true,
    },
    contactPerson: { name: "Jahangir Alam", phone: "01716667788" },
  },
  {
    name: "Barguna Coastal Cyclone Shelter",
    code: "BRG-SHELTER-013",
    location: { type: "Point", coordinates: [90.1250, 22.1500] },
    address: "Amtali Embankment",
    division: "Barishal",
    district: "Barguna",
    upazila: "Amtali",
    capacity: 850,
    currentOccupancy: 420,
    status: "OPEN",
    amenities: {
      hasCleanWater: true,
      hasElectricity: true,
      hasGenerator: true,
      hasMedicalFacility: false,
      separateWomenSpace: true,
    },
    contactPerson: { name: "Siddiqur Rahman", phone: "01918889900" },
  },
  {
    name: "Hatiya Island Emergency Refuge",
    code: "HTY-SHELTER-014",
    location: { type: "Point", coordinates: [91.1200, 22.3600] },
    address: "Nolchira Ghat",
    division: "Chattogram",
    district: "Noakhali",
    upazila: "Hatiya",
    capacity: 1400,
    currentOccupancy: 1400,
    status: "FULL",
    amenities: {
      hasCleanWater: true,
      hasElectricity: false,
      hasGenerator: true,
      hasMedicalFacility: true,
      separateWomenSpace: true,
    },
    contactPerson: { name: "Zahirul Haque", phone: "01812223344" },
  },
  {
    name: "Kurigram River Bank Shelter",
    code: "KGM-SHELTER-015",
    location: { type: "Point", coordinates: [89.6500, 25.8100] },
    address: "Dharla River Basin",
    division: "Rangpur",
    district: "Kurigram",
    upazila: "Kurigram Sadar",
    capacity: 700,
    currentOccupancy: 550,
    status: "OPEN",
    amenities: {
      hasCleanWater: true,
      hasElectricity: true,
      hasGenerator: false,
      hasMedicalFacility: false,
      separateWomenSpace: true,
    },
    contactPerson: { name: "Anisur Rahman", phone: "01719990011" },
  },
  {
    name: "Sirajganj Jamuna Buffer Shelter",
    code: "SRJ-SHELTER-016",
    location: { type: "Point", coordinates: [89.7000, 24.4500] },
    address: "Jamuna Eco Park Road",
    division: "Rajshahi",
    district: "Sirajganj",
    upazila: "Sirajganj Sadar",
    capacity: 900,
    currentOccupancy: 300,
    status: "OPEN",
    amenities: {
      hasCleanWater: true,
      hasElectricity: true,
      hasGenerator: true,
      hasMedicalFacility: true,
      separateWomenSpace: true,
    },
    contactPerson: { name: "Laila Arjumand", phone: "01913332211" },
  },
  {
    name: "Chandpur Meghna Haven Shelter",
    code: "CHP-SHELTER-017",
    location: { type: "Point", coordinates: [90.6500, 23.2300] },
    address: "Boro Station Estuary",
    division: "Chattogram",
    district: "Chandpur",
    upazila: "Chandpur Sadar",
    capacity: 1000,
    currentOccupancy: 650,
    status: "OPEN",
    amenities: {
      hasCleanWater: true,
      hasElectricity: true,
      hasGenerator: false,
      hasMedicalFacility: true,
      separateWomenSpace: true,
    },
    contactPerson: { name: "Imtiaz Ahmed", phone: "01814445566" },
  },
  {
    name: "Patuakhali Kuakata Cyclone Shelter",
    code: "KKT-SHELTER-018",
    location: { type: "Point", coordinates: [90.1200, 21.8200] },
    address: "Kuakata Sea Beach West",
    division: "Barishal",
    district: "Patuakhali",
    upazila: "Kalapara",
    capacity: 1200,
    currentOccupancy: 900,
    status: "OPEN",
    amenities: {
      hasCleanWater: true,
      hasElectricity: true,
      hasGenerator: true,
      hasMedicalFacility: true,
      separateWomenSpace: true,
    },
    contactPerson: { name: "Babul Miah", phone: "01717778899" },
  },
];

async function seed() {
  console.log("[Seed Script] Connecting to database...");
  const db = await connectDB();

  console.log("[Seed Script] Clearing existing shelters collection...");
  await db.collection("shelters").deleteMany({});

  console.log("[Seed Script] Inserting 18 Bangladesh emergency shelters...");
  const result = await db.collection("shelters").insertMany(
    bangladeshShelters.map((s) => ({
      ...s,
      createdAt: new Date(),
      updatedAt: new Date(),
    }))
  );

  console.log(`[Seed Script] Successfully seeded ${result.insertedCount} shelters!`);

  // Verify 2dsphere index
  const indexes = await db.collection("shelters").indexes();
  console.log("[Seed Script] Verified Shelters Collection Indexes:\n", JSON.stringify(indexes, null, 2));

  await closeDB();
  process.exit(0);
}

seed().catch((err) => {
  console.error("[Seed Script] Error during seeding:", err);
  process.exit(1);
});
